### ISSUE TITLE
google-cloud-domains not included in google cloud BOM

### ISSUE THREAD

**Issue by olivierboucher** [googleapis/java-domains#176]
Hi,

First and foremost I apologize for the following the issue format.

You mention the BOM in the README but it seems the google-cloud-domains artifact is not part of the google cloud BOM: https://mvnrepository.com/artifact/com.google.cloud/google-cloud-bom/0.166.0

Is this intentional?

Thanks,

**Comment by Neenu1995** [comment]
Hi @olivierboucher,
Libraries are added to the BOM once they are GA. The java domains library is in the process of being promoted to GA and the README prematurely updated the info based on metadata information available to it. Once the next release goes out, it will be available in the libraries-bom.
